name: portion_control
description: "PortionControl is a minimalist weight management app that helps 
users track food portions in grams and adjust intake based on weight trends. 
With simple logging and dynamic recommendations, it offers a stress-free 
alternative to calorie counting, focusing on sustainable, healthy eating 
habits."

publish_to: 'none'

version: 1.1.2+12

environment:
  sdk: '>=3.9.2 <4.0.0'

dependencies:
  animated_text_kit: ^4.3.0
  bloc: ^9.2.0
  bloc_test: any
  build: any
  collection: ^1.19.1
  drift: ^2.30.1
  drift_flutter: ^0.2.8
  envied: ^1.3.2
  equatable: ^2.0.8
  feedback: ^3.2.0
  fl_chart: ^1.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_email_sender: ^8.0.0
  flutter_html: ^3.0.0
  flutter_local_notifications: ^20.0.0
  flutter_localizations:
    sdk: flutter
  flutter_timezone: ^5.0.1
  flutter_translate:
    git:
      url: https://github.com/Javernaver/flutter_translate.git
      ref: master
  google_fonts: ^8.0.0
  home_widget: ^0.9.0
  in_app_update: ^4.2.5
  intl: ^0.20.2
  meta: any
  mockito: any
  mocktail: ^1.0.4
  nested: ^1.0.0
  package_info_plus: ^9.0.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  resend: ^1.0.0
  shared_preferences: ^2.5.4
  smooth_page_indicator: ^2.0.1
  timezone: any
  url_launcher: ^6.3.2

dev_dependencies:
  build_runner: any
  build_web_compilers: ^4.4.7
  drift_dev: ^2.30.1
  envied_generator: ^1.3.2
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/
    - assets/images/
